### ISSUE TITLE
 Improve Footer with Hover Effects

### ISSUE THREAD

**Issue by sainKunal** [ChiragAgg5k/cal-buddy#6]
Improve Footer with Hover Effects

## Description
The current footer lacks visual engagement. Adding hover effects would enhance user interaction and improve the overall aesthetic.
in Terms And Services ; Privacy Section

## Suggested Improvements
1. **Hover Effects**: Implement subtle hover effects on footer links and icons to make them more interactive.
   - Consider changing the color or adding an underline on hover for links.
   

2. **Additional Effects**: 
   - Add a background change or shadow effect on hover for the footer section itself to make it stand out more.

## Expected Outcome
These changes would make the footer visually appealing and encourage users to engage more with the links provided.

## Screenshots/References
![Screenshot 2024-10-02 012938](https://github.com/user-attachments/assets/5d3fd2c6-5719-4225-981b-46c5214ee2f2)

---

Please let me know what you think about these suggestions. Thanks!

**Comment by sainKunal** [comment]
@ChiragAgg5k Hey I would Like to Work On this Can you assign it to me

**Comment by ChiragAgg5k** [comment]
Hey @sainKunal, thanks for your interest! unfortunately #3 is already working on the footer. I understand you want to work on the hover effects, but that in itself isnt a very big contribution to be considered for hacktoberfest. Your change needs to be big enough for it to count.

for eg, instead of adding hover effects to just footer, you can try adding animations to the entire landing page, or atleast a significant part of it!

Looking forward to your new issue.
